
package com.ups.wsdl.xoltws.rate.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.ups.xmlschema.xoltws.rate.v1.RateRequest;
import com.ups.xmlschema.xoltws.rate.v1.RateResponse;
import com.ups.xmlschema.xoltws.upss.v1.UPSSecurity;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RatePortType", targetNamespace = "http://www.ups.com/WSDL/XOLTWS/Rate/v1.1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.ups.xmlschema.xoltws.upss.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.common.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.error.v1.ObjectFactory.class,
    com.ups.xmlschema.xoltws.rate.v1.ObjectFactory.class
})
public interface RatePortType {


    /**
     * 
     * @param body
     * @param upsSecurity
     * @return
     *     returns com.ups.xmlschema.xoltws.rate.v1.RateResponse
     * @throws RateErrorMessage
     */
    @WebMethod(operationName = "ProcessRate", action = "http://onlinetools.ups.com/webservices/RateBinding/v1.1")
    @WebResult(name = "RateResponse", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Rate/v1.1", partName = "Body")
    public RateResponse processRate(
        @WebParam(name = "RateRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Rate/v1.1", partName = "Body")
        RateRequest body,
        @WebParam(name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true, partName = "UPSSecurity")
        UPSSecurity upsSecurity)
        throws RateErrorMessage
    ;

}
